<header id="top_header">
				<nav id="top_menu">
				<ul>
					<li><h1>GameGEN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1></li>
					<li><a href="index.php">Home<a/></li>
					<li><a href="pc.php">PC</a></li>
					<li>PS4</li>
					<li>Xbox One</li>
					<li>Wii U</li>
					<li>3DS</li>
					<li>Videos</li>
					<li>Reviews</li>
					<li>Movies</li>
					<li>TV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
				</ul>
			</nav>
			</header>